version: '3.3'

services:
  redis:
    image: "redis:alpine"
    environment:
      - REDIS_APPENDONLY=yes
      - REDIS_APPENDFSYNC=always
    volumes:
      - ./data/redis:/data

  php:
    build: 
      context: .
      dockerfile: etc/docker/php.Dockerfile
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/var/www
      - ./etc/php/mwop.ini:/usr/local/etc/php/conf.d/mwop.ini
      - ./etc/cron.d/mwopnet:/etc/cron.d/mwopnet

  caddy:
    build:
      context: .
      dockerfile: etc/docker/caddy.Dockerfile
    depends_on:
      - php
    ports:
      - "8080:8080"
    volumes:
      - ./etc/caddy/Caddyfile.dev:/etc/Caddyfile
