version: '3.3'

services:
  php-fpm:
    build: 
      context: .
      dockerfile: etc/docker/php-fpm.Dockerfile
    env_file:
      - .env
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/mwop.net
      - ./etc/cron.d/www-data:/etc/cron.d/www-data
      - ./etc/php/mwop.ini:/usr/local/etc/php/conf.d/mwop.ini
      - ./etc/php/www.conf:/usr/local/etc/php-fpm.d/www.conf

  nginx:
    build: 
      context: .
      dockerfile: etc/docker/nginx.Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/mwop.net
      - ./etc/nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
