version: '3.3'

services:
  php:
    build: 
      context: .
      dockerfile: etc/docker/php.Dockerfile
    env_file:
      - .env
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
      - ./etc/cron.d/mwopnet:/etc/cron.d/mwopnet
      - ./etc/php/mwop.ini:/usr/local/etc/php/conf.d/mwop.ini

  caddy:
    build:
      context: .
      dockerfile: etc/docker/caddy.Dockerfile
    depends_on:
      - php
    ports:
      - "8080:8080"
    volumes:
      - ./etc/caddy/Caddyfile.dev:/etc/Caddyfile
