version: '3.3'

services:
  php-fpm:
    build: 
      context: .
      dockerfile: etc/docker/php-fpm.Dockerfile
    env_file:
      - .env
    ports:
      - "9000:9000"
    volumes:
      - type: volume
        source: .
        target: /var/www/mwop.net
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./etc/nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/mwop.net
    command: [nginx-debug, '-g', 'daemon off;']
